### ISSUE TITLE
WSO2 WSF/PHP 2.1

### ISSUE THREAD

**Issue by lachezar** [wso2-attic/wsf#4]
Hi,

Would it be possible to put the [WSO2 WSF/PHP 2.1](http://dist.wso2.org/products/wsf/php/2.1.0/wso2-wsf-php-src-2.1.0.tar.gz) on Github?

I have few patches which I would like to apply in a fork.

**Comment by pierrejego** [comment]
Hello, 
I was searching about information to use WSO2 WSF/PHP 2.1 with certificat using 4096 rsa size, and looking to the changelog

      wsf/php/ChangeLog
    
This is already the 2.1 version on this repository.

Had you make any evolution on this version ?

Regards
