### ISSUE TITLE
Configure file missing

### ISSUE THREAD

**Issue by zuzuleinen** [wso2-attic/wsf#6]
I'm trying to install ws02/wsf for PHP. In the installation guide it says that:

Go to the directory where you have extracted the source distribution. Run the following:

```
./configure
make
make install
```

But when I go to php folder I can't find the configure file. Can you give details about installation? Thank you

**Comment by gentunian** [comment]
link forbidden... this is so ironic:

```
WSO2 will no longer continue with any new developments of the WSO2 Web Services Framework for PHP.
We are however handing over the stewardship of the project to the community and the code will be hosted at GitHub.
```
